trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - ReadMe.md
    - LICENSE

name: $(Build.BuildId)

pool:
  vmImage: vs2017-win2016

variables:
  BuildPlatform: 'Any CPU'
  BuildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0
  displayName: Use NuGet 4.8.1
  inputs:
    versionSpec: 4.8.1

- task: NuGetCommand@2
  displayName: 'NuGet restore'

- task: MSBuild@1
  displayName: Build Solution
  inputs:
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'

- powershell: ./Sign-Packages.ps1
  workingDirectory: build
  displayName: Authenticode Sign Artifacts
  env:
    SignClientUser: $(SignClientUser)
    SignClientSecret: $(SignClientSecret)
    SignClientClientId: $(SignClientClientId)
    SignClientTenantId: $(SignClientTenantId)
    SignServiceResourceId: $(SignServiceResourceId)
  condition: and(succeeded(), not(eq(variables['build.reason'], 'PullRequest')), not(eq(variables['SignClientSecret'], '')), not(eq(variables['SignClientUser'], '')))

- task: PublishBuildArtifacts@1
  displayName: Publish Package Artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: NuGet
  condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))